site: Bernat
title: Bernat
description: >-
  Bernat Ferragut - Web3 Design
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Toronto
repo: # site repo [optional]
data-theme: default theme "dark" #| "light"

author:
  name: Bernat Ferragut
  bio: Web3 Design Projects
  username: bernat ferragut # general username
  github: bernatferragut # github username
  twitter: bernatferragut # twitter username
  email: bernatferragut@protonmail.com # email adress

# URL settings
url: "http://bernatferragut.com/" #
baseurl: # leave blank if not wishd
permalink: "http://bernatferragut.com/"
permalink: pretty 

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


